
spring:
  datasource:
    url: jdbc:h2:file:./target/db # jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    password: pw
    username: user
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
debug: true
# liquibase & Flyway